name: Auto PR updated color-thief

on:
  schedule: [{cron: "0 4 1 * *"}]
  workflow_dispatch:

jobs:
  push_to_branch_and_create_pr:
    name: Create PR for updated color-thief
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
          
      - uses: suisei-cn/actions-download-file@v1
        id: colorthief-js
        name: Download JS file for color-thief
        with:
          url: (https://raw.githubusercontent.com/lokesh/color-thief/master/src/color-thief.js)
          auto-match: true
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          commit-message: Update color-thief
          title: Update color-thief
          body: |
            This is an automated PR.
            <sub>[workflow](https://github.com/marvinscham/coverbuilder/blob/master/.github/workflows/main.yml).</sub>
          branch: update-assets
          branch-suffix: "random"
